
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PomodoroTimerDominio.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Aluno
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Aluno()
    {

        this.Sessao = new HashSet<Sessao>();

    }


    public int Id { get; set; }

    public string Nome { get; set; }

    public int Rm { get; set; }

    public System.DateTime DtNascimento { get; set; }

    public int CursoId { get; set; }

    public int LoginId { get; set; }



    public virtual Curso Curso { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sessao> Sessao { get; set; }

    public virtual Login Login { get; set; }

}

}
