//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PomodoroTimerDominio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessao
    {
        public int Id { get; set; }
        public int TipoId { get; set; }
        public int AlunoId { get; set; }
        public int MateriaId { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual TipoSessao TipoSessao { get; set; }
    }
}
